version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "7000:80"

  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - AUTH_SERVICE_URL=http://auth-service:6001
      - USER_SERVICE_URL=http://user-service:6002
    depends_on:
      - auth-service
      - user-service

  auth-service:
    build: ./auth-service
    ports:
      - "6001:6001"
    environment:
      - JWT_SECRET=supersecretkey
      - USER_SERVICE_URL=http://user-service:6002
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    ports:
      - "6002:6002"
    environment:
      - JWT_SECRET=supersecretkey
